const HTTP_CODE = {
    SUCCESS: 200,
    INTERNAL_ERROR: 500,
    REQUEST_ERROR: 400
};

const ERROR_CODE = {};

const STATUS_CODE = {
    SUCCESS: 0,
    ERROR: -1
};

export { HTTP_CODE, ERROR_CODE, STATUS_CODE };
